name: Resolve which editions should build
inputs:
  scope:
    description: Include test sh files like assert.sh
    type: choice
    options:
      - test
      - run
    required: false
    default: 'run'
outputs:
  utils-path:
    value: ${{ steps.export-scripts.outputs.utils-path }}
  utils-sources:
    value: ${{ steps.export-scripts.outputs.utils-path }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: export-scripts
      run: |
        TEMP_FOLDER=$(mktemp -d)
        find "${TEMP_FOLDER}" -name "*.sh" -type f -print0 2>/dev/null | xargs -0 cp -t 
        echo "utils-path=${TEMP_FOLDER}" >> ${GITHUB_OUTPUT}

        
