name: Resolve which editions should build
inputs:
  scope:
    description: Include test sh files like assert.sh
    type: choice
    options:
      - test
      - run
    required: false
    default: 'run'
outputs:
  path:
    value: ${{ steps.export-scripts.outputs.export-path }}
  sources:
    value: ${{ steps.export-scripts.outputs.export-sources }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: export-scripts
      run: |
        TEMP_FOLDER=$(mktemp -d)
        CAT_SORUCES=""
        for i in $(find "./${{ github.action_path }}" -name "*.sh" -type f -maxdepth 1 2>/dev/null); do
            cp "$i" "${TEMP_FOLDER}"
            CAT_SORUCES+=$(cat "$i")
            CAT_SORUCES+=$'\n'
        done

        echo "export-path=${TEMP_FOLDER}" >> ${GITHUB_OUTPUT}
        echo "export-sources=${CAT_SORUCES}" >> ${GITHUB_OUTPUT}

        
